# Copyright (c) 2024, 2026, Oracle and/or its affiliates. All rights reserved.
# The Universal Permissive License (UPL), Version 1.0 as shown at https://oss.oracle.com/licenses/upl/

kind: StressChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: nginx-mem-1
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: nginx
  mode: all
  stressors:
    memory:
      workers: 4
      size: 600MiB
  duration: 120s
