# Copyright (c) 2024, 2026, Oracle and/or its affiliates. All rights reserved.
# The Universal Permissive License (UPL), Version 1.0 as shown at https://oss.oracle.com/licenses/upl/

###############################################################################
# Kerberos credentials (when deploy_hdfs = true)
#
# Generated by Terraform and delivered to the cluster inside the operator's
# bootstrap manifests (platform.tf -> the kerberos-creds Secret). Consumed by
# the KDC and the HDFS keytab init-containers.
###############################################################################

resource "random_password" "kdc_db" {
  count   = var.deploy_hdfs ? 1 : 0
  length  = 32
  special = false
}

resource "random_password" "kadmin" {
  count   = var.deploy_hdfs ? 1 : 0
  length  = 32
  special = false
}

resource "random_password" "hadoop_user" {
  count   = var.deploy_hdfs ? 1 : 0
  length  = 24
  special = false
}
