###############################################################################
# Kerberos credentials (when deploy_hdfs = true)
#
# Generated by Terraform and delivered to the cluster inside the operator's
# bootstrap manifests (platform.tf -> the kerberos-creds Secret). Consumed by
# the KDC and the HDFS keytab init-containers.
###############################################################################

resource "random_password" "kdc_db" {
  count   = var.deploy_hdfs ? 1 : 0
  length  = 32
  special = false
}

resource "random_password" "kadmin" {
  count   = var.deploy_hdfs ? 1 : 0
  length  = 32
  special = false
}

resource "random_password" "hadoop_user" {
  count   = var.deploy_hdfs ? 1 : 0
  length  = 24
  special = false
}
